# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16f8a00072c5b38bc4f6bb450204845cf8441ce9c93ffa8897c8965307f9d1340bda71ceee529cef5901ace8c628335e84726df23686d507e8b0d52c1fac1899

test:
  secret_key_base: 090c001537581aa825bcb43571a1d6f18cfff88303cdf0347203f791169a78f27c50fb4c3d63f6970687530f47561c274bf67069ec20c33f840ca92ab8577dcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
