# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2caff05ca4f9e8a6e3ec21647f2b50f6848ed9b1f78f740da48fabd89a93c09ff06a1657aed95cda303296ecfde71445d6413e1f97f0ba58e1fef6d1c11e8e05

test:
  secret_key_base: a7c9061ca6ec5e12b43e0d313686c401a9c6d81f9418c03902c401384cad17efc4f3ab1749e9174c14d88768b5efc4e721ec708b03edddfab7e1b4865afcf3bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
